# Generated by Django 5.2.1 on 2025-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=255, unique=True)),
                ('position', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'db_table': 'airports_tbl',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['airport_code'], name='airports_tb_airport_91df56_idx'), models.Index(fields=['position', 'duration'], name='airports_tb_positio_756b9a_idx')],
            },
        ),
    ]
