# Generated by Django 5.2.1 on 2025-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='master_airport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='parent_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
